districts_data = [{'state_name':'ANDAMAN NICOBAR','name':'NICOBAR'},
{'state_name':'ANDAMAN NICOBAR','name':'NORTH MIDDLE ANDAMAN'},
{'state_name':'ANDAMAN NICOBAR','name':'SOUTH ANDAMAN'},
{'state_name':'ANDHRA PRADESH','name':'ALLURI SITARAMA RAJU'},
{'state_name':'ANDHRA PRADESH','name':'ANAKAPALLI'},
{'state_name':'ANDHRA PRADESH','name':'ANANTAPUR'},
{'state_name':'ANDHRA PRADESH','name':'ANNAMAYA'},
{'state_name':'ANDHRA PRADESH','name':'BAPATLA'},
{'state_name':'ANDHRA PRADESH','name':'CHITTOOR'},
{'state_name':'ANDHRA PRADESH','name':'EAST GODAVARI'},
{'state_name':'ANDHRA PRADESH','name':'ELURU'},
{'state_name':'ANDHRA PRADESH','name':'GUNTUR'},
{'state_name':'ANDHRA PRADESH','name':'KADAPA'},
{'state_name':'ANDHRA PRADESH','name':'KAKINADA'},
{'state_name':'ANDHRA PRADESH','name':'KONASEEMA'},
{'state_name':'ANDHRA PRADESH','name':'KRISHNA'},
{'state_name':'ANDHRA PRADESH','name':'KURNOOL'},
{'state_name':'ANDHRA PRADESH','name':'MANYAM'},
{'state_name':'ANDHRA PRADESH','name':'N T RAMA RAO'},
{'state_name':'ANDHRA PRADESH','name':'NANDYAL'},
{'state_name':'ANDHRA PRADESH','name':'NELLORE'},
{'state_name':'ANDHRA PRADESH','name':'PALNADU'},
{'state_name':'ANDHRA PRADESH','name':'PRAKASAM'},
{'state_name':'ANDHRA PRADESH','name':'SRI BALAJI'},
{'state_name':'ANDHRA PRADESH','name':'SRI SATYA SAI'},
{'state_name':'ANDHRA PRADESH','name':'SRIKAKULAM'},
{'state_name':'ANDHRA PRADESH','name':'VISAKHAPATNAM'},
{'state_name':'ANDHRA PRADESH','name':'VIZIANAGARAM'},
{'state_name':'ANDHRA PRADESH','name':'WEST GODAVARI'},
{'state_name':'ARUNACHAL PRADESH','name':'ANJAW'},
{'state_name':'ARUNACHAL PRADESH','name':'BICHOM'},
{'state_name':'ARUNACHAL PRADESH','name':'CHANGLANG'},
{'state_name':'ARUNACHAL PRADESH','name':'DIBANG VALLEY'},
{'state_name':'ARUNACHAL PRADESH','name':'EAST KAMENG'},
{'state_name':'ARUNACHAL PRADESH','name':'EAST SIANG'},
{'state_name':'ARUNACHAL PRADESH','name':'KAMLE'},
{'state_name':'ARUNACHAL PRADESH','name':'KEYI PANYOR'},
{'state_name':'ARUNACHAL PRADESH','name':'KRA DAADI'},
{'state_name':'ARUNACHAL PRADESH','name':'KURUNG KUMEY'},
{'state_name':'ARUNACHAL PRADESH','name':'LEPA RADA'},
{'state_name':'ARUNACHAL PRADESH','name':'LOHIT'},
{'state_name':'ARUNACHAL PRADESH','name':'LONGDING'},
{'state_name':'ARUNACHAL PRADESH','name':'LOWER DIBANG VALLEY'},
{'state_name':'ARUNACHAL PRADESH','name':'LOWER SIANG'},
{'state_name':'ARUNACHAL PRADESH','name':'LOWER SUBANSIRI'},
{'state_name':'ARUNACHAL PRADESH','name':'NAMSAI'},
{'state_name':'ARUNACHAL PRADESH','name':'PAKKE KESSANG'},
{'state_name':'ARUNACHAL PRADESH','name':'PAPUM PARE'},
{'state_name':'ARUNACHAL PRADESH','name':'SHI YOMI'},
{'state_name':'ARUNACHAL PRADESH','name':'SIANG'},
{'state_name':'ARUNACHAL PRADESH','name':'TAWANG'},
{'state_name':'ARUNACHAL PRADESH','name':'TIRAP'},
{'state_name':'ARUNACHAL PRADESH','name':'UPPER SIANG'},
{'state_name':'ARUNACHAL PRADESH','name':'UPPER SUBANSIRI'},
{'state_name':'ARUNACHAL PRADESH','name':'WEST KAMENG'},
{'state_name':'ARUNACHAL PRADESH','name':'WEST SIANG'},
{'state_name':'ASSAM','name':'BAJALI'},
{'state_name':'ASSAM','name':'BAKSA'},
{'state_name':'ASSAM','name':'BARPETA'},
{'state_name':'ASSAM','name':'BISWANATH'},
{'state_name':'ASSAM','name':'BONGAIGAON'},
{'state_name':'ASSAM','name':'CACHAR'},
{'state_name':'ASSAM','name':'CHARAIDEO'},
{'state_name':'ASSAM','name':'CHIRANG'},
{'state_name':'ASSAM','name':'DARRANG'},
{'state_name':'ASSAM','name':'DHEMAJI'},
{'state_name':'ASSAM','name':'DHUBRI'},
{'state_name':'ASSAM','name':'DIBRUGARH'},
{'state_name':'ASSAM','name':'DIMA HASAO'},
{'state_name':'ASSAM','name':'GOALPARA'},
{'state_name':'ASSAM','name':'GOLAGHAT'},
{'state_name':'ASSAM','name':'HAILAKANDI'},
{'state_name':'ASSAM','name':'HOJAI'},
{'state_name':'ASSAM','name':'JORHAT'},
{'state_name':'ASSAM','name':'KAMRUP METROPOLITAN'},
{'state_name':'ASSAM','name':'KAMRUP RURAL'},
{'state_name':'ASSAM','name':'KARBI ANGLONG'},
{'state_name':'ASSAM','name':'KARIMGANJ'},
{'state_name':'ASSAM','name':'KOKRAJHAR'},
{'state_name':'ASSAM','name':'LAKHIMPUR'},
{'state_name':'ASSAM','name':'MAJULI'},
{'state_name':'ASSAM','name':'MORIGAON'},
{'state_name':'ASSAM','name':'NAGAON'},
{'state_name':'ASSAM','name':'NALBARI'},
{'state_name':'ASSAM','name':'SIVASAGAR'},
{'state_name':'ASSAM','name':'SONITPUR'},
{'state_name':'ASSAM','name':'SOUTH SALMARA-MANKACHAR'},
{'state_name':'ASSAM','name':'TAMULPUR'},
{'state_name':'ASSAM','name':'TINSUKIA'},
{'state_name':'ASSAM','name':'UDALGURI'},
{'state_name':'ASSAM','name':'WEST KARBI ANGLONG'},
{'state_name':'BIHAR','name':'ARARIA'},
{'state_name':'BIHAR','name':'ARWAL'},
{'state_name':'BIHAR','name':'AURANGABAD'},
{'state_name':'BIHAR','name':'BANKA'},
{'state_name':'BIHAR','name':'BEGUSARAI'},
{'state_name':'BIHAR','name':'BHAGALPUR'},
{'state_name':'BIHAR','name':'BHOJPUR'},
{'state_name':'BIHAR','name':'BUXAR'},
{'state_name':'BIHAR','name':'DARBHANGA'},
{'state_name':'BIHAR','name':'EAST CHAMPARAN'},
{'state_name':'BIHAR','name':'GAYA'},
{'state_name':'BIHAR','name':'GOPALGANJ'},
{'state_name':'BIHAR','name':'JAMUI'},
{'state_name':'BIHAR','name':'JEHANABAD'},
{'state_name':'BIHAR','name':'KAIMUR'},
{'state_name':'BIHAR','name':'KATIHAR'},
{'state_name':'BIHAR','name':'KHAGARIA'},
{'state_name':'BIHAR','name':'KISHANGANJ'},
{'state_name':'BIHAR','name':'LAKHISARAI'},
{'state_name':'BIHAR','name':'MADHEPURA'},
{'state_name':'BIHAR','name':'MADHUBANI'},
{'state_name':'BIHAR','name':'MUNGER'},
{'state_name':'BIHAR','name':'MUZAFFARPUR'},
{'state_name':'BIHAR','name':'NALANDA'},
{'state_name':'BIHAR','name':'NAWADA'},
{'state_name':'BIHAR','name':'PATNA'},
{'state_name':'BIHAR','name':'PURNIA'},
{'state_name':'BIHAR','name':'ROHTAS'},
{'state_name':'BIHAR','name':'SAHARSA'},
{'state_name':'BIHAR','name':'SAMASTIPUR'},
{'state_name':'BIHAR','name':'SARAN'},
{'state_name':'BIHAR','name':'SHEIKHPURA'},
{'state_name':'BIHAR','name':'SHEOHAR'},
{'state_name':'BIHAR','name':'SITAMARHI'},
{'state_name':'BIHAR','name':'SIWAN'},
{'state_name':'BIHAR','name':'SUPAUL'},
{'state_name':'BIHAR','name':'VAISHALI'},
{'state_name':'BIHAR','name':'WEST CHAMPARAN'},
{'state_name':'CHANDIGARH','name':'CHANDIGARH'},
{'state_name':'CHHATTISGARH','name':'BALOD'},
{'state_name':'CHHATTISGARH','name':'BALODA BAZAR'},
{'state_name':'CHHATTISGARH','name':'BALRAMPUR'},
{'state_name':'CHHATTISGARH','name':'BASTAR'},
{'state_name':'CHHATTISGARH','name':'BEMETARA'},
{'state_name':'CHHATTISGARH','name':'BIJAPUR'},
{'state_name':'CHHATTISGARH','name':'BILASPUR'},
{'state_name':'CHHATTISGARH','name':'DANTEWADA'},
{'state_name':'CHHATTISGARH','name':'DHAMTARI'},
{'state_name':'CHHATTISGARH','name':'DURG'},
{'state_name':'CHHATTISGARH','name':'GARIABAND'},
{'state_name':'CHHATTISGARH','name':'GAURELA PENDRA MARWAHI'},
{'state_name':'CHHATTISGARH','name':'JANJGIR CHAMPA'},
{'state_name':'CHHATTISGARH','name':'JASHPUR'},
{'state_name':'CHHATTISGARH','name':'KABIRDHAM'},
{'state_name':'CHHATTISGARH','name':'KANKER'},
{'state_name':'CHHATTISGARH','name':'KHAIRAGARH'},
{'state_name':'CHHATTISGARH','name':'KONDAGAON'},
{'state_name':'CHHATTISGARH','name':'KORBA'},
{'state_name':'CHHATTISGARH','name':'KORIYA'},
{'state_name':'CHHATTISGARH','name':'MAHASAMUND'},
{'state_name':'CHHATTISGARH','name':'MANENDRAGARH'},
{'state_name':'CHHATTISGARH','name':'MOHLA MANPUR'},
{'state_name':'CHHATTISGARH','name':'MUNGELI'},
{'state_name':'CHHATTISGARH','name':'NARAYANPUR'},
{'state_name':'CHHATTISGARH','name':'RAIGARH'},
{'state_name':'CHHATTISGARH','name':'RAIPUR'},
{'state_name':'CHHATTISGARH','name':'RAJNANDGAON'},
{'state_name':'CHHATTISGARH','name':'SAKTI'},
{'state_name':'CHHATTISGARH','name':'SARANGARH BILAIGARH'},
{'state_name':'CHHATTISGARH','name':'SUKMA'},
{'state_name':'CHHATTISGARH','name':'SURAJPUR'},
{'state_name':'CHHATTISGARH','name':'SURGUJA'},
{'state_name':'DADRA NAGAR HAVELI AND DAMAN AND DIU','name':'DADRA AND NAGAR HAVELI'},
{'state_name':'DADRA NAGAR HAVELI AND DAMAN AND DIU','name':'DAMAN'},
{'state_name':'DADRA NAGAR HAVELI AND DAMAN AND DIU','name':'DIU'},
{'state_name':'DELHI','name':'CENTRAL DELHI'},
{'state_name':'DELHI','name':'EAST DELHI'},
{'state_name':'DELHI','name':'NEW DELHI'},
{'state_name':'DELHI','name':'NORTH DELHI'},
{'state_name':'DELHI','name':'NORTH EAST DELHI'},
{'state_name':'DELHI','name':'NORTH WEST DELHI'},
{'state_name':'DELHI','name':'SHAHDARA'},
{'state_name':'DELHI','name':'SOUTH DELHI'},
{'state_name':'DELHI','name':'SOUTH EAST DELHI'},
{'state_name':'DELHI','name':'SOUTH WEST DELHI'},
{'state_name':'DELHI','name':'WEST DELHI'},
{'state_name':'GOA','name':'NORTH GOA'},
{'state_name':'GOA','name':'SOUTH GOA'},
{'state_name':'GUJARAT','name':'AHMEDABAD'},
{'state_name':'GUJARAT','name':'AMRELI'},
{'state_name':'GUJARAT','name':'ANAND'},
{'state_name':'GUJARAT','name':'ARAVALLI'},
{'state_name':'GUJARAT','name':'BANASKANTHA'},
{'state_name':'GUJARAT','name':'BHARUCH'},
{'state_name':'GUJARAT','name':'BHAVNAGAR'},
{'state_name':'GUJARAT','name':'BOTAD'},
{'state_name':'GUJARAT','name':'CHHOTA UDAIPUR'},
{'state_name':'GUJARAT','name':'DAHOD'},
{'state_name':'GUJARAT','name':'DANG'},
{'state_name':'GUJARAT','name':'DEVBHOOMI DWARKA'},
{'state_name':'GUJARAT','name':'GANDHINAGAR'},
{'state_name':'GUJARAT','name':'GIR SOMNATH'},
{'state_name':'GUJARAT','name':'JAMNAGAR'},
{'state_name':'GUJARAT','name':'JUNAGADH'},
{'state_name':'GUJARAT','name':'KHEDA'},
{'state_name':'GUJARAT','name':'KUTCH'},
{'state_name':'GUJARAT','name':'MAHISAGAR'},
{'state_name':'GUJARAT','name':'MEHSANA'},
{'state_name':'GUJARAT','name':'MORBI'},
{'state_name':'GUJARAT','name':'NARMADA'},
{'state_name':'GUJARAT','name':'NAVSARI'},
{'state_name':'GUJARAT','name':'PANCHMAHAL'},
{'state_name':'GUJARAT','name':'PATAN'},
{'state_name':'GUJARAT','name':'PORBANDAR'},
{'state_name':'GUJARAT','name':'RAJKOT'},
{'state_name':'GUJARAT','name':'SABARKANTHA'},
{'state_name':'GUJARAT','name':'SURAT'},
{'state_name':'GUJARAT','name':'SURENDRANAGAR'},
{'state_name':'GUJARAT','name':'TAPI'},
{'state_name':'GUJARAT','name':'VADODARA'},
{'state_name':'GUJARAT','name':'VALSAD'},
{'state_name':'HARYANA','name':'AMBALA'},
{'state_name':'HARYANA','name':'BHIWANI'},
{'state_name':'HARYANA','name':'CHARKHI DADRI'},
{'state_name':'HARYANA','name':'FARIDABAD'},
{'state_name':'HARYANA','name':'FATEHABAD'},
{'state_name':'HARYANA','name':'GURUGRAM'},
{'state_name':'HARYANA','name':'HISAR'},
{'state_name':'HARYANA','name':'JHAJJAR'},
{'state_name':'HARYANA','name':'JIND'},
{'state_name':'HARYANA','name':'KAITHAL'},
{'state_name':'HARYANA','name':'KARNAL'},
{'state_name':'HARYANA','name':'KURUKSHETRA'},
{'state_name':'HARYANA','name':'MAHENDRAGARH'},
{'state_name':'HARYANA','name':'NUH'},
{'state_name':'HARYANA','name':'PALWAL'},
{'state_name':'HARYANA','name':'PANCHKULA'},
{'state_name':'HARYANA','name':'PANIPAT'},
{'state_name':'HARYANA','name':'REWARI'},
{'state_name':'HARYANA','name':'ROHTAK'},
{'state_name':'HARYANA','name':'SIRSA'},
{'state_name':'HARYANA','name':'SONIPAT'},
{'state_name':'HARYANA','name':'YAMUNANAGAR'},
{'state_name':'HIMACHAL PRADESH','name':'BILASPUR'},
{'state_name':'HIMACHAL PRADESH','name':'CHAMBA'},
{'state_name':'HIMACHAL PRADESH','name':'HAMIRPUR'},
{'state_name':'HIMACHAL PRADESH','name':'KANGRA'},
{'state_name':'HIMACHAL PRADESH','name':'KINNAUR'},
{'state_name':'HIMACHAL PRADESH','name':'KULLU'},
{'state_name':'HIMACHAL PRADESH','name':'LAHAUL SPITI'},
{'state_name':'HIMACHAL PRADESH','name':'MANDI'},
{'state_name':'HIMACHAL PRADESH','name':'SHIMLA'},
{'state_name':'HIMACHAL PRADESH','name':'SIRMAUR'},
{'state_name':'HIMACHAL PRADESH','name':'SOLAN'},
{'state_name':'HIMACHAL PRADESH','name':'UNA'},
{'state_name':'JAMMU KASHMIR','name':'ANANTNAG'},
{'state_name':'JAMMU KASHMIR','name':'BANDIPORA'},
{'state_name':'JAMMU KASHMIR','name':'BARAMULLA'},
{'state_name':'JAMMU KASHMIR','name':'BUDGAM'},
{'state_name':'JAMMU KASHMIR','name':'DODA'},
{'state_name':'JAMMU KASHMIR','name':'GANDERBAL'},
{'state_name':'JAMMU KASHMIR','name':'JAMMU'},
{'state_name':'JAMMU KASHMIR','name':'KATHUA'},
{'state_name':'JAMMU KASHMIR','name':'KISHTWAR'},
{'state_name':'JAMMU KASHMIR','name':'KULGAM'},
{'state_name':'JAMMU KASHMIR','name':'KUPWARA'},
{'state_name':'JAMMU KASHMIR','name':'POONCH'},
{'state_name':'JAMMU KASHMIR','name':'PULWAMA'},
{'state_name':'JAMMU KASHMIR','name':'RAJOURI'},
{'state_name':'JAMMU KASHMIR','name':'RAMBAN'},
{'state_name':'JAMMU KASHMIR','name':'REASI'},
{'state_name':'JAMMU KASHMIR','name':'SAMBA'},
{'state_name':'JAMMU KASHMIR','name':'SHOPIAN'},
{'state_name':'JAMMU KASHMIR','name':'SRINAGAR'},
{'state_name':'JAMMU KASHMIR','name':'UDHAMPUR'},
{'state_name':'JHARKHAND','name':'BOKARO'},
{'state_name':'JHARKHAND','name':'CHATRA'},
{'state_name':'JHARKHAND','name':'DEOGHAR'},
{'state_name':'JHARKHAND','name':'DHANBAD'},
{'state_name':'JHARKHAND','name':'DUMKA'},
{'state_name':'JHARKHAND','name':'EAST SINGHBHUM'},
{'state_name':'JHARKHAND','name':'GARHWA'},
{'state_name':'JHARKHAND','name':'GIRIDIH'},
{'state_name':'JHARKHAND','name':'GODDA'},
{'state_name':'JHARKHAND','name':'GUMLA'},
{'state_name':'JHARKHAND','name':'HAZARIBAGH'},
{'state_name':'JHARKHAND','name':'JAMTARA'},
{'state_name':'JHARKHAND','name':'KHUNTI'},
{'state_name':'JHARKHAND','name':'KODERMA'},
{'state_name':'JHARKHAND','name':'LATEHAR'},
{'state_name':'JHARKHAND','name':'LOHARDAGA'},
{'state_name':'JHARKHAND','name':'PAKUR'},
{'state_name':'JHARKHAND','name':'PALAMU'},
{'state_name':'JHARKHAND','name':'RAMGARH'},
{'state_name':'JHARKHAND','name':'RANCHI'},
{'state_name':'JHARKHAND','name':'SAHEBGANJ'},
{'state_name':'JHARKHAND','name':'SERAIKELA KHARSAWAN'},
{'state_name':'JHARKHAND','name':'SIMDEGA'},
{'state_name':'JHARKHAND','name':'WEST SINGHBHUM'},
{'state_name':'KARNATAKA','name':'BAGALKOT'},
{'state_name':'KARNATAKA','name':'BANGALORE RURAL'},
{'state_name':'KARNATAKA','name':'BANGALORE URBAN'},
{'state_name':'KARNATAKA','name':'BELGAUM'},
{'state_name':'KARNATAKA','name':'BELLARY'},
{'state_name':'KARNATAKA','name':'BIDAR'},
{'state_name':'KARNATAKA','name':'CHAMARAJANAGAR'},
{'state_name':'KARNATAKA','name':'CHIKKABALLAPUR'},
{'state_name':'KARNATAKA','name':'CHIKKAMAGALURU'},
{'state_name':'KARNATAKA','name':'CHITRADURGA'},
{'state_name':'KARNATAKA','name':'DAKSHINA KANNADA'},
{'state_name':'KARNATAKA','name':'DAVANAGERE'},
{'state_name':'KARNATAKA','name':'DHARWAD'},
{'state_name':'KARNATAKA','name':'GADAG'},
{'state_name':'KARNATAKA','name':'HASSAN'},
{'state_name':'KARNATAKA','name':'HAVERI'},
{'state_name':'KARNATAKA','name':'KALABURAGI'},
{'state_name':'KARNATAKA','name':'KODAGU'},
{'state_name':'KARNATAKA','name':'KOLAR'},
{'state_name':'KARNATAKA','name':'KOPPAL'},
{'state_name':'KARNATAKA','name':'MANDYA'},
{'state_name':'KARNATAKA','name':'MYSORE'},
{'state_name':'KARNATAKA','name':'RAICHUR'},
{'state_name':'KARNATAKA','name':'RAMANAGARA'},
{'state_name':'KARNATAKA','name':'SHIMOGA'},
{'state_name':'KARNATAKA','name':'TUMKUR'},
{'state_name':'KARNATAKA','name':'UDUPI'},
{'state_name':'KARNATAKA','name':'UTTARA KANNADA'},
{'state_name':'KARNATAKA','name':'VIJAYANAGARA'},
{'state_name':'KARNATAKA','name':'VIJAYAPURA'},
{'state_name':'KARNATAKA','name':'YADGIR'},
{'state_name':'KERALA','name':'ALAPPUZHA'},
{'state_name':'KERALA','name':'ERNAKULAM'},
{'state_name':'KERALA','name':'IDUKKI'},
{'state_name':'KERALA','name':'KANNUR'},
{'state_name':'KERALA','name':'KASARAGOD'},
{'state_name':'KERALA','name':'KOLLAM'},
{'state_name':'KERALA','name':'KOTTAYAM'},
{'state_name':'KERALA','name':'KOZHIKODE'},
{'state_name':'KERALA','name':'MALAPPURAM'},
{'state_name':'KERALA','name':'PALAKKAD'},
{'state_name':'KERALA','name':'PATHANAMTHITTA'},
{'state_name':'KERALA','name':'THIRUVANANTHAPURAM'},
{'state_name':'KERALA','name':'THRISSUR'},
{'state_name':'KERALA','name':'WAYANAD'},
{'state_name':'LADAKH','name':'KARGIL'},
{'state_name':'LADAKH','name':'LEH'},
{'state_name':'LAKSHADWEEP','name':'LAKSHADWEEP'},
{'state_name':'MADHYA PRADESH','name':'AGAR MALWA'},
{'state_name':'MADHYA PRADESH','name':'ALIRAJPUR'},
{'state_name':'MADHYA PRADESH','name':'ANUPPUR'},
{'state_name':'MADHYA PRADESH','name':'ASHOKNAGAR'},
{'state_name':'MADHYA PRADESH','name':'BALAGHAT'},
{'state_name':'MADHYA PRADESH','name':'BARWANI'},
{'state_name':'MADHYA PRADESH','name':'BETUL'},
{'state_name':'MADHYA PRADESH','name':'BHIND'},
{'state_name':'MADHYA PRADESH','name':'BHOPAL'},
{'state_name':'MADHYA PRADESH','name':'BURHANPUR'},
{'state_name':'MADHYA PRADESH','name':'CHHATARPUR'},
{'state_name':'MADHYA PRADESH','name':'CHHINDWARA'},
{'state_name':'MADHYA PRADESH','name':'DAMOH'},
{'state_name':'MADHYA PRADESH','name':'DATIA'},
{'state_name':'MADHYA PRADESH','name':'DEWAS'},
{'state_name':'MADHYA PRADESH','name':'DHAR'},
{'state_name':'MADHYA PRADESH','name':'DINDORI'},
{'state_name':'MADHYA PRADESH','name':'GUNA'},
{'state_name':'MADHYA PRADESH','name':'GWALIOR'},
{'state_name':'MADHYA PRADESH','name':'HARDA'},
{'state_name':'MADHYA PRADESH','name':'HOSHANGABAD'},
{'state_name':'MADHYA PRADESH','name':'INDORE'},
{'state_name':'MADHYA PRADESH','name':'JABALPUR'},
{'state_name':'MADHYA PRADESH','name':'JHABUA'},
{'state_name':'MADHYA PRADESH','name':'KATNI'},
{'state_name':'MADHYA PRADESH','name':'KHANDWA'},
{'state_name':'MADHYA PRADESH','name':'KHARGONE'},
{'state_name':'MADHYA PRADESH','name':'MAIHAR'},
{'state_name':'MADHYA PRADESH','name':'MANDLA'},
{'state_name':'MADHYA PRADESH','name':'MANDSAUR'},
{'state_name':'MADHYA PRADESH','name':'MAUGANJ'},
{'state_name':'MADHYA PRADESH','name':'MORENA'},
{'state_name':'MADHYA PRADESH','name':'NARSINGHPUR'},
{'state_name':'MADHYA PRADESH','name':'NEEMUCH'},
{'state_name':'MADHYA PRADESH','name':'NIWARI'},
{'state_name':'MADHYA PRADESH','name':'PANDHURNA'},
{'state_name':'MADHYA PRADESH','name':'PANNA'},
{'state_name':'MADHYA PRADESH','name':'RAISEN'},
{'state_name':'MADHYA PRADESH','name':'RAJGARH'},
{'state_name':'MADHYA PRADESH','name':'RATLAM'},
{'state_name':'MADHYA PRADESH','name':'REWA'},
{'state_name':'MADHYA PRADESH','name':'SAGAR'},
{'state_name':'MADHYA PRADESH','name':'SATNA'},
{'state_name':'MADHYA PRADESH','name':'SEHORE'},
{'state_name':'MADHYA PRADESH','name':'SEONI'},
{'state_name':'MADHYA PRADESH','name':'SHAHDOL'},
{'state_name':'MADHYA PRADESH','name':'SHAJAPUR'},
{'state_name':'MADHYA PRADESH','name':'SHEOPUR'},
{'state_name':'MADHYA PRADESH','name':'SHIVPURI'},
{'state_name':'MADHYA PRADESH','name':'SIDHI'},
{'state_name':'MADHYA PRADESH','name':'SINGRAULI'},
{'state_name':'MADHYA PRADESH','name':'TIKAMGARH'},
{'state_name':'MADHYA PRADESH','name':'UJJAIN'},
{'state_name':'MADHYA PRADESH','name':'UMARIA'},
{'state_name':'MADHYA PRADESH','name':'VIDISHA'},
{'state_name':'MAHARASHTRA','name':'AHMEDNAGAR'},
{'state_name':'MAHARASHTRA','name':'AKOLA'},
{'state_name':'MAHARASHTRA','name':'AMRAVATI'},
{'state_name':'MAHARASHTRA','name':'AURANGABAD'},
{'state_name':'MAHARASHTRA','name':'BEED'},
{'state_name':'MAHARASHTRA','name':'BHANDARA'},
{'state_name':'MAHARASHTRA','name':'BULDHANA'},
{'state_name':'MAHARASHTRA','name':'CHANDRAPUR'},
{'state_name':'MAHARASHTRA','name':'DHULE'},
{'state_name':'MAHARASHTRA','name':'GADCHIROLI'},
{'state_name':'MAHARASHTRA','name':'GONDIA'},
{'state_name':'MAHARASHTRA','name':'HINGOLI'},
{'state_name':'MAHARASHTRA','name':'JALGAON'},
{'state_name':'MAHARASHTRA','name':'JALNA'},
{'state_name':'MAHARASHTRA','name':'KOLHAPUR'},
{'state_name':'MAHARASHTRA','name':'LATUR'},
{'state_name':'MAHARASHTRA','name':'MUMBAI CITY'},
{'state_name':'MAHARASHTRA','name':'MUMBAI SUBURBAN'},
{'state_name':'MAHARASHTRA','name':'NAGPUR'},
{'state_name':'MAHARASHTRA','name':'NANDED'},
{'state_name':'MAHARASHTRA','name':'NANDURBAR'},
{'state_name':'MAHARASHTRA','name':'NASHIK'},
{'state_name':'MAHARASHTRA','name':'OSMANABAD'},
{'state_name':'MAHARASHTRA','name':'PALGHAR'},
{'state_name':'MAHARASHTRA','name':'PARBHANI'},
{'state_name':'MAHARASHTRA','name':'PUNE'},
{'state_name':'MAHARASHTRA','name':'RAIGAD'},
{'state_name':'MAHARASHTRA','name':'RATNAGIRI'},
{'state_name':'MAHARASHTRA','name':'SANGLI'},
{'state_name':'MAHARASHTRA','name':'SATARA'},
{'state_name':'MAHARASHTRA','name':'SINDHUDURG'},
{'state_name':'MAHARASHTRA','name':'SOLAPUR'},
{'state_name':'MAHARASHTRA','name':'THANE'},
{'state_name':'MAHARASHTRA','name':'WARDHA'},
{'state_name':'MAHARASHTRA','name':'WASHIM'},
{'state_name':'MAHARASHTRA','name':'YAVATMAL'},
{'state_name':'MANIPUR','name':'BISHNUPUR'},
{'state_name':'MANIPUR','name':'CHANDEL'},
{'state_name':'MANIPUR','name':'CHURACHANDPUR'},
{'state_name':'MANIPUR','name':'IMPHAL EAST'},
{'state_name':'MANIPUR','name':'IMPHAL WEST'},
{'state_name':'MANIPUR','name':'JIRIBAM'},
{'state_name':'MANIPUR','name':'KAKCHING'},
{'state_name':'MANIPUR','name':'KAMJONG'},
{'state_name':'MANIPUR','name':'KANGPOKPI'},
{'state_name':'MANIPUR','name':'NONEY'},
{'state_name':'MANIPUR','name':'PHERZAWL'},
{'state_name':'MANIPUR','name':'SENAPATI'},
{'state_name':'MANIPUR','name':'TAMENGLONG'},
{'state_name':'MANIPUR','name':'TENGNOUPAL'},
{'state_name':'MANIPUR','name':'THOUBAL'},
{'state_name':'MANIPUR','name':'UKHRUL'},
{'state_name':'MEGHALAYA','name':'EAST GARO HILLS'},
{'state_name':'MEGHALAYA','name':'EAST JAINTIA HILLS'},
{'state_name':'MEGHALAYA','name':'EAST KHASI HILLS'},
{'state_name':'MEGHALAYA','name':'MAIRANG'},
{'state_name':'MEGHALAYA','name':'NORTH GARO HILLS'},
{'state_name':'MEGHALAYA','name':'RI BHOI'},
{'state_name':'MEGHALAYA','name':'SOUTH GARO HILLS'},
{'state_name':'MEGHALAYA','name':'SOUTH WEST GARO HILLS'},
{'state_name':'MEGHALAYA','name':'SOUTH WEST KHASI HILLS'},
{'state_name':'MEGHALAYA','name':'WEST GARO HILLS'},
{'state_name':'MEGHALAYA','name':'WEST JAINTIA HILLS'},
{'state_name':'MEGHALAYA','name':'WEST KHASI HILLS'},
{'state_name':'MIZORAM','name':'AIZAWL'},
{'state_name':'MIZORAM','name':'CHAMPHAI'},
{'state_name':'MIZORAM','name':'HNAHTHIAL'},
{'state_name':'MIZORAM','name':'KHAWZAWL'},
{'state_name':'MIZORAM','name':'KOLASIB'},
{'state_name':'MIZORAM','name':'LAWNGTLAI'},
{'state_name':'MIZORAM','name':'LUNGLEI'},
{'state_name':'MIZORAM','name':'MAMIT'},
{'state_name':'MIZORAM','name':'SAIHA'},
{'state_name':'MIZORAM','name':'SAITUAL'},
{'state_name':'MIZORAM','name':'SERCHHIP'},
{'state_name':'NAGALAND','name':'CHUMUKEDIMA'},
{'state_name':'NAGALAND','name':'DIMAPUR'},
{'state_name':'NAGALAND','name':'KIPHIRE'},
{'state_name':'NAGALAND','name':'KOHIMA'},
{'state_name':'NAGALAND','name':'LONGLENG'},
{'state_name':'NAGALAND','name':'MOKOKCHUNG'},
{'state_name':'NAGALAND','name':'MON'},
{'state_name':'NAGALAND','name':'NIULAND'},
{'state_name':'NAGALAND','name':'NOKLAK'},
{'state_name':'NAGALAND','name':'PEREN'},
{'state_name':'NAGALAND','name':'PHEK'},
{'state_name':'NAGALAND','name':'SHAMATOR'},
{'state_name':'NAGALAND','name':'TSEMINYU'},
{'state_name':'NAGALAND','name':'TUENSANG'},
{'state_name':'NAGALAND','name':'WOKHA'},
{'state_name':'NAGALAND','name':'ZUNHEBOTO'},
{'state_name':'ODISHA','name':'ANGUL'},
{'state_name':'ODISHA','name':'BALANGIR'},
{'state_name':'ODISHA','name':'BALASORE'},
{'state_name':'ODISHA','name':'BARGARH'},
{'state_name':'ODISHA','name':'BHADRAK'},
{'state_name':'ODISHA','name':'BOUDH'},
{'state_name':'ODISHA','name':'CUTTACK'},
{'state_name':'ODISHA','name':'DEBAGARH'},
{'state_name':'ODISHA','name':'DHENKANAL'},
{'state_name':'ODISHA','name':'GAJAPATI'},
{'state_name':'ODISHA','name':'GANJAM'},
{'state_name':'ODISHA','name':'JAGATSINGHPUR'},
{'state_name':'ODISHA','name':'JAJPUR'},
{'state_name':'ODISHA','name':'JHARSUGUDA'},
{'state_name':'ODISHA','name':'KALAHANDI'},
{'state_name':'ODISHA','name':'KANDHAMAL'},
{'state_name':'ODISHA','name':'KENDRAPARA'},
{'state_name':'ODISHA','name':'KENDUJHAR'},
{'state_name':'ODISHA','name':'KHORDHA'},
{'state_name':'ODISHA','name':'KORAPUT'},
{'state_name':'ODISHA','name':'MALKANGIRI'},
{'state_name':'ODISHA','name':'MAYURBHANJ'},
{'state_name':'ODISHA','name':'NABARANGPUR'},
{'state_name':'ODISHA','name':'NAYAGARH'},
{'state_name':'ODISHA','name':'NUAPADA'},
{'state_name':'ODISHA','name':'PURI'},
{'state_name':'ODISHA','name':'RAYAGADA'},
{'state_name':'ODISHA','name':'SAMBALPUR'},
{'state_name':'ODISHA','name':'SUBARNAPUR'},
{'state_name':'ODISHA','name':'SUNDERGARH'},
{'state_name':'PUDUCHERRY','name':'KARAIKAL'},
{'state_name':'PUDUCHERRY','name':'MAHE'},
{'state_name':'PUDUCHERRY','name':'PUDUCHERRY'},
{'state_name':'PUDUCHERRY','name':'YANAM'},
{'state_name':'PUNJAB','name':'AMRITSAR'},
{'state_name':'PUNJAB','name':'BARNALA'},
{'state_name':'PUNJAB','name':'BATHINDA'},
{'state_name':'PUNJAB','name':'FARIDKOT'},
{'state_name':'PUNJAB','name':'FATEHGARH SAHIB'},
{'state_name':'PUNJAB','name':'FAZILKA'},
{'state_name':'PUNJAB','name':'FIROZPUR'},
{'state_name':'PUNJAB','name':'GURDASPUR'},
{'state_name':'PUNJAB','name':'HOSHIARPUR'},
{'state_name':'PUNJAB','name':'JALANDHAR'},
{'state_name':'PUNJAB','name':'KAPURTHALA'},
{'state_name':'PUNJAB','name':'LUDHIANA'},
{'state_name':'PUNJAB','name':'MALERKOTLA'},
{'state_name':'PUNJAB','name':'MANSA'},
{'state_name':'PUNJAB','name':'MOGA'},
{'state_name':'PUNJAB','name':'MOHALI'},
{'state_name':'PUNJAB','name':'MUKTSAR'},
{'state_name':'PUNJAB','name':'PATHANKOT'},
{'state_name':'PUNJAB','name':'PATIALA'},
{'state_name':'PUNJAB','name':'RUPNAGAR'},
{'state_name':'PUNJAB','name':'SANGRUR'},
{'state_name':'PUNJAB','name':'SHAHEED BHAGAT SINGH NAGAR'},
{'state_name':'PUNJAB','name':'TARN TARAN'},
{'state_name':'RAJASTHAN','name':'AJMER'},
{'state_name':'RAJASTHAN','name':'ALWAR'},
{'state_name':'RAJASTHAN','name':'ANUPGARH'},
{'state_name':'RAJASTHAN','name':'BALOTRA'},
{'state_name':'RAJASTHAN','name':'BANSWARA'},
{'state_name':'RAJASTHAN','name':'BARAN'},
{'state_name':'RAJASTHAN','name':'BARMER'},
{'state_name':'RAJASTHAN','name':'BEAWAR'},
{'state_name':'RAJASTHAN','name':'BHARATPUR'},
{'state_name':'RAJASTHAN','name':'BHILWARA'},
{'state_name':'RAJASTHAN','name':'BIKANER'},
{'state_name':'RAJASTHAN','name':'BUNDI'},
{'state_name':'RAJASTHAN','name':'CHITTORGARH'},
{'state_name':'RAJASTHAN','name':'CHURU'},
{'state_name':'RAJASTHAN','name':'DAUSA'},
{'state_name':'RAJASTHAN','name':'DEEG'},
{'state_name':'RAJASTHAN','name':'DHOLPUR'},
{'state_name':'RAJASTHAN','name':'DIDWANA KUCHAMAN'},
{'state_name':'RAJASTHAN','name':'DUDU'},
{'state_name':'RAJASTHAN','name':'DUNGARPUR'},
{'state_name':'RAJASTHAN','name':'GANGAPUR CITY'},
{'state_name':'RAJASTHAN','name':'HANUMANGARH'},
{'state_name':'RAJASTHAN','name':'JAIPUR'},
{'state_name':'RAJASTHAN','name':'JAIPUR RURAL'},
{'state_name':'RAJASTHAN','name':'JAISALMER'},
{'state_name':'RAJASTHAN','name':'JALORE'},
{'state_name':'RAJASTHAN','name':'JHALAWAR'},
{'state_name':'RAJASTHAN','name':'JHUNJHUNU'},
{'state_name':'RAJASTHAN','name':'JODHPUR'},
{'state_name':'RAJASTHAN','name':'JODHPUR RURAL'},
{'state_name':'RAJASTHAN','name':'KARAULI'},
{'state_name':'RAJASTHAN','name':'KEKRI'},
{'state_name':'RAJASTHAN','name':'KHAIRTHAL TIJARA'},
{'state_name':'RAJASTHAN','name':'KOTA'},
{'state_name':'RAJASTHAN','name':'KOTPUTLI BEHROR'},
{'state_name':'RAJASTHAN','name':'NAGAUR'},
{'state_name':'RAJASTHAN','name':'NEEM KA THANA'},
{'state_name':'RAJASTHAN','name':'PALI'},
{'state_name':'RAJASTHAN','name':'PHALODI'},
{'state_name':'RAJASTHAN','name':'PRATAPGARH'},
{'state_name':'RAJASTHAN','name':'RAJSAMAND'},
{'state_name':'RAJASTHAN','name':'SALUMBAR'},
{'state_name':'RAJASTHAN','name':'SANCHORE'},
{'state_name':'RAJASTHAN','name':'SAWAI MADHOPUR'},
{'state_name':'RAJASTHAN','name':'SHAHPURA'},
{'state_name':'RAJASTHAN','name':'SIKAR'},
{'state_name':'RAJASTHAN','name':'SIROHI'},
{'state_name':'RAJASTHAN','name':'SRI GANGANAGAR'},
{'state_name':'RAJASTHAN','name':'TONK'},
{'state_name':'RAJASTHAN','name':'UDAIPUR'},
{'state_name':'SIKKIM','name':'EAST SIKKIM'},
{'state_name':'SIKKIM','name':'NORTH SIKKIM'},
{'state_name':'SIKKIM','name':'PAKYONG'},
{'state_name':'SIKKIM','name':'SORENG'},
{'state_name':'SIKKIM','name':'SOUTH SIKKIM'},
{'state_name':'SIKKIM','name':'WEST SIKKIM'},
{'state_name':'TAMIL NADU','name':'ARIYALUR'},
{'state_name':'TAMIL NADU','name':'CHENGALPATTU'},
{'state_name':'TAMIL NADU','name':'CHENNAI'},
{'state_name':'TAMIL NADU','name':'COIMBATORE'},
{'state_name':'TAMIL NADU','name':'CUDDALORE'},
{'state_name':'TAMIL NADU','name':'DHARMAPURI'},
{'state_name':'TAMIL NADU','name':'DINDIGUL'},
{'state_name':'TAMIL NADU','name':'ERODE'},
{'state_name':'TAMIL NADU','name':'KALLAKURICHI'},
{'state_name':'TAMIL NADU','name':'KANCHIPURAM'},
{'state_name':'TAMIL NADU','name':'KANYAKUMARI'},
{'state_name':'TAMIL NADU','name':'KARUR'},
{'state_name':'TAMIL NADU','name':'KRISHNAGIRI'},
{'state_name':'TAMIL NADU','name':'MADURAI'},
{'state_name':'TAMIL NADU','name':'MAYILADUTHURAI'},
{'state_name':'TAMIL NADU','name':'NAGAPATTINAM'},
{'state_name':'TAMIL NADU','name':'NAMAKKAL'},
{'state_name':'TAMIL NADU','name':'NILGIRIS'},
{'state_name':'TAMIL NADU','name':'PERAMBALUR'},
{'state_name':'TAMIL NADU','name':'PUDUKKOTTAI'},
{'state_name':'TAMIL NADU','name':'RAMANATHAPURAM'},
{'state_name':'TAMIL NADU','name':'RANIPET'},
{'state_name':'TAMIL NADU','name':'SALEM'},
{'state_name':'TAMIL NADU','name':'SIVAGANGA'},
{'state_name':'TAMIL NADU','name':'TENKASI'},
{'state_name':'TAMIL NADU','name':'THANJAVUR'},
{'state_name':'TAMIL NADU','name':'THENI'},
{'state_name':'TAMIL NADU','name':'THOOTHUKUDI'},
{'state_name':'TAMIL NADU','name':'TIRUCHIRAPPALLI'},
{'state_name':'TAMIL NADU','name':'TIRUNELVELI'},
{'state_name':'TAMIL NADU','name':'TIRUPATTUR'},
{'state_name':'TAMIL NADU','name':'TIRUPPUR'},
{'state_name':'TAMIL NADU','name':'TIRUVALLUR'},
{'state_name':'TAMIL NADU','name':'TIRUVANNAMALAI'},
{'state_name':'TAMIL NADU','name':'TIRUVARUR'},
{'state_name':'TAMIL NADU','name':'VELLORE'},
{'state_name':'TAMIL NADU','name':'VILUPPURAM'},
{'state_name':'TAMIL NADU','name':'VIRUDHUNAGAR'},
{'state_name':'TELANGANA','name':'ADILABAD'},
{'state_name':'TELANGANA','name':'BHADRADRI KOTHAGUDEM'},
{'state_name':'TELANGANA','name':'HANAMKONDA'},
{'state_name':'TELANGANA','name':'HYDERABAD'},
{'state_name':'TELANGANA','name':'JAGTIAL'},
{'state_name':'TELANGANA','name':'JANGAON'},
{'state_name':'TELANGANA','name':'JAYASHANKAR'},
{'state_name':'TELANGANA','name':'JOGULAMBA'},
{'state_name':'TELANGANA','name':'KAMAREDDY'},
{'state_name':'TELANGANA','name':'KARIMNAGAR'},
{'state_name':'TELANGANA','name':'KHAMMAM'},
{'state_name':'TELANGANA','name':'KOMARAM BHEEM'},
{'state_name':'TELANGANA','name':'MAHABUBABAD'},
{'state_name':'TELANGANA','name':'MAHBUBNAGAR'},
{'state_name':'TELANGANA','name':'MANCHERIAL'},
{'state_name':'TELANGANA','name':'MEDAK'},
{'state_name':'TELANGANA','name':'MEDCHAL MALKAJGIRI'},
{'state_name':'TELANGANA','name':'MULUGU'},
{'state_name':'TELANGANA','name':'NAGARKURNOOL'},
{'state_name':'TELANGANA','name':'NALGONDA'},
{'state_name':'TELANGANA','name':'NARAYANPET'},
{'state_name':'TELANGANA','name':'NIRMAL'},
{'state_name':'TELANGANA','name':'NIZAMABAD'},
{'state_name':'TELANGANA','name':'PEDDAPALLI'},
{'state_name':'TELANGANA','name':'RAJANNA SIRCILLA'},
{'state_name':'TELANGANA','name':'RANGA REDDY'},
{'state_name':'TELANGANA','name':'SANGAREDDY'},
{'state_name':'TELANGANA','name':'SIDDIPET'},
{'state_name':'TELANGANA','name':'SURYAPET'},
{'state_name':'TELANGANA','name':'VIKARABAD'},
{'state_name':'TELANGANA','name':'WANAPARTHY'},
{'state_name':'TELANGANA','name':'WARANGAL'},
{'state_name':'TELANGANA','name':'YADADRI BHUVANAGIRI'},
{'state_name':'TRIPURA','name':'DHALAI'},
{'state_name':'TRIPURA','name':'GOMATI'},
{'state_name':'TRIPURA','name':'KHOWAI'},
{'state_name':'TRIPURA','name':'NORTH TRIPURA'},
{'state_name':'TRIPURA','name':'SEPAHIJALA'},
{'state_name':'TRIPURA','name':'SOUTH TRIPURA'},
{'state_name':'TRIPURA','name':'UNAKOTI'},
{'state_name':'TRIPURA','name':'WEST TRIPURA'},
{'state_name':'UTTAR PRADESH','name':'AGRA'},
{'state_name':'UTTAR PRADESH','name':'ALIGARH'},
{'state_name':'UTTAR PRADESH','name':'AMBEDKAR NAGAR'},
{'state_name':'UTTAR PRADESH','name':'AMETHI'},
{'state_name':'UTTAR PRADESH','name':'AMROHA'},
{'state_name':'UTTAR PRADESH','name':'AURAIYA'},
{'state_name':'UTTAR PRADESH','name':'AYODHYA'},
{'state_name':'UTTAR PRADESH','name':'AZAMGARH'},
{'state_name':'UTTAR PRADESH','name':'BAGHPAT'},
{'state_name':'UTTAR PRADESH','name':'BAHRAICH'},
{'state_name':'UTTAR PRADESH','name':'BALLIA'},
{'state_name':'UTTAR PRADESH','name':'BALRAMPUR'},
{'state_name':'UTTAR PRADESH','name':'BANDA'},
{'state_name':'UTTAR PRADESH','name':'BARABANKI'},
{'state_name':'UTTAR PRADESH','name':'BAREILLY'},
{'state_name':'UTTAR PRADESH','name':'BASTI'},
{'state_name':'UTTAR PRADESH','name':'BHADOHI'},
{'state_name':'UTTAR PRADESH','name':'BIJNOR'},
{'state_name':'UTTAR PRADESH','name':'BUDAUN'},
{'state_name':'UTTAR PRADESH','name':'BULANDSHAHR'},
{'state_name':'UTTAR PRADESH','name':'CHANDAULI'},
{'state_name':'UTTAR PRADESH','name':'CHITRAKOOT'},
{'state_name':'UTTAR PRADESH','name':'DEORIA'},
{'state_name':'UTTAR PRADESH','name':'ETAH'},
{'state_name':'UTTAR PRADESH','name':'ETAWAH'},
{'state_name':'UTTAR PRADESH','name':'FARRUKHABAD'},
{'state_name':'UTTAR PRADESH','name':'FATEHPUR'},
{'state_name':'UTTAR PRADESH','name':'FIROZABAD'},
{'state_name':'UTTAR PRADESH','name':'GAUTAM BUDDHA NAGAR'},
{'state_name':'UTTAR PRADESH','name':'GHAZIABAD'},
{'state_name':'UTTAR PRADESH','name':'GHAZIPUR'},
{'state_name':'UTTAR PRADESH','name':'GONDA'},
{'state_name':'UTTAR PRADESH','name':'GORAKHPUR'},
{'state_name':'UTTAR PRADESH','name':'HAMIRPUR'},
{'state_name':'UTTAR PRADESH','name':'HAPUR'},
{'state_name':'UTTAR PRADESH','name':'HARDOI'},
{'state_name':'UTTAR PRADESH','name':'HATHRAS'},
{'state_name':'UTTAR PRADESH','name':'JALAUN'},
{'state_name':'UTTAR PRADESH','name':'JAUNPUR'},
{'state_name':'UTTAR PRADESH','name':'JHANSI'},
{'state_name':'UTTAR PRADESH','name':'KANNAUJ'},
{'state_name':'UTTAR PRADESH','name':'KANPUR DEHAT'},
{'state_name':'UTTAR PRADESH','name':'KANPUR NAGAR'},
{'state_name':'UTTAR PRADESH','name':'KASGANJ'},
{'state_name':'UTTAR PRADESH','name':'KAUSHAMBI'},
{'state_name':'UTTAR PRADESH','name':'KUSHINAGAR'},
{'state_name':'UTTAR PRADESH','name':'LAKHIMPUR KHERI'},
{'state_name':'UTTAR PRADESH','name':'LALITPUR'},
{'state_name':'UTTAR PRADESH','name':'LUCKNOW'},
{'state_name':'UTTAR PRADESH','name':'MAHARAJGANJ'},
{'state_name':'UTTAR PRADESH','name':'MAHOBA'},
{'state_name':'UTTAR PRADESH','name':'MAINPURI'},
{'state_name':'UTTAR PRADESH','name':'MATHURA'},
{'state_name':'UTTAR PRADESH','name':'MAU'},
{'state_name':'UTTAR PRADESH','name':'MEERUT'},
{'state_name':'UTTAR PRADESH','name':'MIRZAPUR'},
{'state_name':'UTTAR PRADESH','name':'MORADABAD'},
{'state_name':'UTTAR PRADESH','name':'MUZAFFARNAGAR'},
{'state_name':'UTTAR PRADESH','name':'PILIBHIT'},
{'state_name':'UTTAR PRADESH','name':'PRATAPGARH'},
{'state_name':'UTTAR PRADESH','name':'PRAYAGRAJ'},
{'state_name':'UTTAR PRADESH','name':'RAEBARELI'},
{'state_name':'UTTAR PRADESH','name':'RAMPUR'},
{'state_name':'UTTAR PRADESH','name':'SAHARANPUR'},
{'state_name':'UTTAR PRADESH','name':'SAMBHAL'},
{'state_name':'UTTAR PRADESH','name':'SANT KABIR NAGAR'},
{'state_name':'UTTAR PRADESH','name':'SHAHJAHANPUR'},
{'state_name':'UTTAR PRADESH','name':'SHAMLI'},
{'state_name':'UTTAR PRADESH','name':'SHRAVASTI'},
{'state_name':'UTTAR PRADESH','name':'SIDDHARTHNAGAR'},
{'state_name':'UTTAR PRADESH','name':'SITAPUR'},
{'state_name':'UTTAR PRADESH','name':'SONBHADRA'},
{'state_name':'UTTAR PRADESH','name':'SULTANPUR'},
{'state_name':'UTTAR PRADESH','name':'UNNAO'},
{'state_name':'UTTAR PRADESH','name':'VARANASI'},
{'state_name':'UTTARAKHAND','name':'ALMORA'},
{'state_name':'UTTARAKHAND','name':'BAGESHWAR'},
{'state_name':'UTTARAKHAND','name':'CHAMOLI'},
{'state_name':'UTTARAKHAND','name':'CHAMPAWAT'},
{'state_name':'UTTARAKHAND','name':'DEHRADUN'},
{'state_name':'UTTARAKHAND','name':'HARIDWAR'},
{'state_name':'UTTARAKHAND','name':'NAINITAL'},
{'state_name':'UTTARAKHAND','name':'PAURI'},
{'state_name':'UTTARAKHAND','name':'PITHORAGARH'},
{'state_name':'UTTARAKHAND','name':'RUDRAPRAYAG'},
{'state_name':'UTTARAKHAND','name':'TEHRI'},
{'state_name':'UTTARAKHAND','name':'UDHAM SINGH NAGAR'},
{'state_name':'UTTARAKHAND','name':'UTTARKASHI'},
{'state_name':'WEST BENGAL','name':'ALIPURDUAR'},
{'state_name':'WEST BENGAL','name':'BANKURA'},
{'state_name':'WEST BENGAL','name':'BIRBHUM'},
{'state_name':'WEST BENGAL','name':'COOCH BEHAR'},
{'state_name':'WEST BENGAL','name':'DAKSHIN DINAJPUR'},
{'state_name':'WEST BENGAL','name':'DARJEELING'},
{'state_name':'WEST BENGAL','name':'HOOGHLY'},
{'state_name':'WEST BENGAL','name':'HOWRAH'},
{'state_name':'WEST BENGAL','name':'JALPAIGURI'},
{'state_name':'WEST BENGAL','name':'JHARGRAM'},
{'state_name':'WEST BENGAL','name':'KALIMPONG'},
{'state_name':'WEST BENGAL','name':'KOLKATA'},
{'state_name':'WEST BENGAL','name':'MALDA'},
{'state_name':'WEST BENGAL','name':'MURSHIDABAD'},
{'state_name':'WEST BENGAL','name':'NADIA'},
{'state_name':'WEST BENGAL','name':'NORTH 24 PARGANAS'},
{'state_name':'WEST BENGAL','name':'PASCHIM BARDHAMAN'},
{'state_name':'WEST BENGAL','name':'PASCHIM MEDINIPUR'},
{'state_name':'WEST BENGAL','name':'PURBA BARDHAMAN'},
{'state_name':'WEST BENGAL','name':'PURBA MEDINIPUR'},
{'state_name':'WEST BENGAL','name':'PURULIA'},
{'state_name':'WEST BENGAL','name':'SOUTH 24 PARGANAS'},
{'state_name':'WEST BENGAL','name':'UTTAR DINAJPUR'},
]