# Generated by Django 5.1.2 on 2024-10-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='plan_expiration_date',
            field=models.DateField(editable=False),
        ),
    ]
