# Generated by Django 5.1.2 on 2024-10-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='plan_expiration_date',
            field=models.DateField(),
        ),
    ]
