# Generated by Django 5.1.2 on 2024-10-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_door_numbeer_customer_door_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='father_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='flat_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='flat_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='landmark',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subscription_date',
            field=models.DateField(null=True),
        ),
    ]
