# Generated by Django 5.1.2 on 2024-10-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_customer_father_name_alter_customer_flat_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='plan_expiration_date',
            field=models.DateField(null=True),
        ),
    ]
