# Generated by Django 5.1.2 on 2024-11-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_payment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bjp_membership_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='refer_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
