# Generated by Django 5.1.2 on 2024-11-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_customer_bjp_membership_number_customer_refer_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cell_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
