# Generated by Django 5.1.2 on 2024-11-17 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_customer_cell_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cell_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
